/**
 * Run all pending migrations against DATABASE_URL.
 *
 * Usage:
 *   npm run db:migrate --workspace=@task/api
 *
 * Migration files live in src/db/migrations/ and are generated by
 * `npm run db:generate` (drizzle-kit) when the schema changes.
 */
import pg from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { config } from '../config';

const { Pool } = pg;

const main = async (): Promise<void> => {
  const pool = new Pool({ connectionString: config.DATABASE_URL, max: 1 });
  const db = drizzle(pool);
  const migrationsFolder = resolve(dirname(fileURLToPath(import.meta.url)), 'migrations');

  // eslint-disable-next-line no-console
  console.log(`Running migrations from ${migrationsFolder}`);
  await migrate(db, { migrationsFolder });
  await pool.end();
  // eslint-disable-next-line no-console
  console.log('Migrations applied');
};

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('Migration failed:', err);
  process.exit(1);
});
